Repository spandey1296/hacktoberfest-2023, pull requests merged in 2023-10, with the labels that each got.

#1 this is for the developer for the reference.
  What-is-Full-Stack-Develo.9187520.powerpoint.pptx
Labels: hacktoberfest-accepted, hacktoberfest2023

#8 Create 01 string_find_all.cpp
  01 string_find_all.cpp
  linked_list.cpp
Labels: hacktoberfest-accepted, hacktoberfest2023

#12 Dhruvil 03 - React code using Parcel.js as Bundler.
  React-03/App.js
  React-03/README.md
  React-03/index.css
  React-03/index.html
  React-03/package-lock.json
  React-03/package.json
Labels: hacktoberfest-accepted, hacktoberfest2023

#9 project-with-copilot-chat
  project-with-copilot-chat.zip
Labels: hacktoberfest-accepted, hacktoberfest2023

#15 Create SideBar.js
  SideBar.js
Labels: hacktoberfest-accepted, hacktoberfest2023

#14 stock_data_generator
  stock_data_generator.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest2023

#16 Open AI
  OpenAI-scaled.jpeg
Labels: hacktoberfest-accepted, hacktoberfest2023

#17 ChatGPT_API_openai
  ChatGPT_API_openai.pdf
Labels: hacktoberfest-accepted, hacktoberfest2023

#19 GenAI updates
  GenAI updates from our partner ecosystem.pdf
Labels: hacktoberfest-accepted, hacktoberfest2023

#18 hashmap
  hashmap.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest2023

#26 Create bmi_calculator.py
  bmi_calculator.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest2023

#20 Non Overlapping Substring
  NonOverlappingSubstring.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest2023

#25 Create Frontend.html
  Frontend.html
Labels: hacktoberfest-accepted, hacktoberfest2023, hacktober2023-approved

#21 Create BFS.cpp
  BFS.cpp
Labels: hacktoberfest-accepted, hacktoberfest2023, hacktober2023-approved

#23 Create Prims.cpp
  Prims.cpp
Labels: hacktoberfest-accepted, hacktoberfest2023, hacktober2023-approved

#24 Create TreeTraversal.cpp
  TreeTraversal.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest2023, hacktober2023-approved

#22 Create Krushals.cpp
  Krushals.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest2023, hacktober2023-approved

#27 Create redundant_paranthesis.cpp
  redundant_paranthesis.cpp
Labels: hacktoberfest-accepted, hacktoberfest2023, hacktober2023-approved

#30 Accept My PR
  Screenshot (12).png
Labels: hacktoberfest-accepted, hacktoberfest2023, hacktober2023-approved

#28 Create cycle_detection_undirected.cpp
  cycle_detection_undirected.cpp
  level_order_tree_input.txt
Labels: hacktoberfest-accepted, hacktoberfest2023, hacktober2023-approved

#29 Added MNIST CNN
  CNN_MNIST.py
Labels: hacktoberfest-accepted, hacktoberfest2023, hacktober2023-approved

#33 Add files via upload
  atm_mini_project.py
Labels: hacktoberfest-accepted, hacktoberfest2023, hacktober2023-approved

#31 Create CombinationSum.java
  CombinationSum.java
Labels: hacktoberfest-accepted, hacktoberfest2023, hacktober2023-approved

#35 Added new Java program
  DuplicateWordCount.java
Labels: hacktoberfest-accepted, hacktoberfest2023, hacktober2023-approved

#34 Create StringAnagramsListStream.java
  StringAnagramsListStream.java
Labels: hacktoberfest-accepted, hacktoberfest2023, hacktober2023-approved
